import { Teacher, Class, City, Gender,Course } from '@/types/teachers';

const teachers: Teacher[] = [
  {
    id: "1",
    name: "John Doe",
    class: Class.first_year,
    course : Course.ARCHITECTURE_EVOLUEE,
    email: "john.doe@example.com",
    gender: Gender.MALE,
    points: 85,
    city: City.ALGER,
    phone_number: 1234567890,
  },
  {
    id: "2",
    name: "Jane Smith",
    class: Class.second_year,
    course : Course.Reaseau,
    email: "jane.smith@example.com",
    gender: Gender.FEMALE,
    points: 75,
    city: City.SIDI_BEL_Abbes,
    phone_number: 9876543210,
  },
  {
    id: "3",
    name: "Michael Johnson",
    class: Class.third_year,
    course : Course.Analyse,
    email: "michael.johnson@example.com",
    gender: Gender.MALE,
    points: 90,
    city: City.ALGER,
    phone_number: 2345678901,
  },
  {
    id: "4",
    name: "Emily Brown",
    class: Class.fourth_year,
    course : Course.ARCHITECTURE_EVOLUEE,
    email: "emily.brown@example.com",
    gender: Gender.FEMALE,
    points: 80,
    city: City.SIDI_BEL_Abbes,
    phone_number: 8765432109,
  },
  {
    id: "5",
    name: "Daniel Wilson",
    class: Class.fifth_year,
    course : Course.Analyse,
    email: "daniel.wilson@example.com",
    gender: Gender.MALE,
    points: 88,
    city: City.ALGER,
    phone_number: 3456789012,
  },
  {
    id: "6",
    name: "Sophia Martinez",
    class: Class.first_year,
    course : Course.Reaseau,
    email: "sophia.martinez@example.com",
    gender: Gender.FEMALE,
    points: 78,
    city: City.SIDI_BEL_Abbes,
    phone_number: 7654321098,
  },
  {
    id: "7",
    name: "Matthew Anderson",
    class: Class.second_year,
    course : Course.ARCHITECTURE_EVOLUEE,
    email: "matthew.anderson@example.com",
    gender: Gender.MALE,
    points: 92,
    city: City.ALGER,
    phone_number: 4567890123,
  },
  {
    id: "8",
    name: "Olivia Garcia",
    class: Class.third_year,
    course : Course.Analyse,
    email: "olivia.garcia@example.com",
    gender: Gender.FEMALE,
    points: 82,
    city: City.SIDI_BEL_Abbes,
    phone_number: 6543210987,
  },
  {
    id: "9",
    name: "David Lopez",
    class: Class.fourth_year,
    course : Course.Reaseau,
    email: "david.lopez@example.com",
    gender: Gender.MALE,
    points: 86,
    city: City.ALGER,
    phone_number: 5678901234,
  },
  {
    id: "10",
    name: "Emma Rodriguez",
    class: Class.fifth_year,
    course : Course.ARCHITECTURE_EVOLUEE,
    email: "emma.rodriguez@example.com",
    gender: Gender.FEMALE,
    points: 79,
    city: City.SIDI_BEL_Abbes,
    phone_number: 5432109876,
  },
  {
    id: "11",
    name: "James Hernandez",
    class: Class.first_year,
    course : Course.Analyse,
    email: "james.hernandez@example.com",
    gender: Gender.MALE,
    points: 88,
    city: City.ALGER,
    phone_number: 6789012345,
  },
  {
    id: "12",
    name: "Isabella Martinez",
    class: Class.second_year,
    course : Course.Reaseau,
    email: "isabella.martinez@example.com",
    gender: Gender.FEMALE,
    points: 75,
    city: City.SIDI_BEL_Abbes,
    phone_number: 4321098765,
  },
  {
    id: "13",
    name: "Ethan Nguyen",
    class: Class.third_year,
    course : Course.Reaseau,
    email: "ethan.nguyen@example.com",
    gender: Gender.MALE,
    points: 91,
    city: City.ALGER,
    phone_number: 7890123456,
  },
  {
    id: "14",
    name: "Ava Perez",
    class: Class.fourth_year,
    course : Course.Reaseau,
    email: "ava.perez@example.com",
    gender: Gender.FEMALE,
    points: 83,
    city: City.SIDI_BEL_Abbes,
    phone_number: 3210987654,
  },
  {
    id: "15",
    name: "Alexander Taylor",
    class: Class.fifth_year,
    course : Course.Reaseau,
    email: "alexander.taylor@example.com",
    gender: Gender.MALE,
    points: 87,
    city: City.ALGER,
    phone_number: 8901234567,
  },
  {
    id: "16",
    name: "Mia King",
    class: Class.first_year,
    course : Course.Reaseau,
    email: "mia.king@example.com",
    gender: Gender.FEMALE,
    points: 80,
    city: City.SIDI_BEL_Abbes,
    phone_number: 2109876543,
  },
  {
    id: "17",
    name: "William Brown",
    class: Class.second_year,
    course : Course.Reaseau,
    email: "william.brown@example.com",
    gender: Gender.MALE,
    points: 89,
    city: City.ALGER,
    phone_number: 9012345678,
  },
  {
    id: "18",
    name: "Sofia Rodriguez",
    class: Class.third_year,
    course : Course.Reaseau,
    email: "sofia.rodriguez@example.com",
    gender: Gender.FEMALE,
    points: 77,
    city: City.SIDI_BEL_Abbes,
    phone_number: 1098765432,
  },
  {
    id: "19",
    name: "Benjamin Garcia",
    class: Class.fourth_year,
    course : Course.Analyse,
    email: "benjamin.garcia@example.com",
    gender: Gender.MALE,
    points: 84,
    city: City.ALGER,
    phone_number: 1234567890,
  },
  {
    id: "20",
    name: "Charlotte Martinez",
    class: Class.fifth_year,
    course : Course.ARCHITECTURE_EVOLUEE,
    email: "charlotte.martinez@example.com",
    gender: Gender.FEMALE,
    points: 81,
    city: City.SIDI_BEL_Abbes,
    phone_number: 9876543210,
  },
];

export default teachers;
