import type {Metadata} from "next";
import {getRedirectUrl} from "@/app/actions/iam";
import {IAMWrapper} from "@/layout/iam";

export const metadata: Metadata = {
    title: 'Madaurus',
    description: 'Generated by create next app',
    icons: ['/assets/icons/logo.jpg'],
};
export  default async  function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const res = await getRedirectUrl()

    return (
        <main>
        <IAMWrapper url={res?.url}>

            {children}
        </IAMWrapper>
        </main>
    );
}
