import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SideBar } from "@/components/layouts/sidebar";
// import { Suspense } from "react";
import { Montserrat } from 'next/font/google';
import NavBar from "@/components/layouts/navbar";
import { Toaster } from "@/components/ui/sonner";

const monts = Montserrat({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['latin'],
	style: ['normal'],
	variable: '--font-montserrat',
	display: 'swap',
});
export const metadata: Metadata = {
	title: 'Madaurus',
	description: 'Generated by create next app',
	icons: ['/assets/icons/logo.jpg'],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
         <body  className={` flex ${monts.className} `} >
      {/* <Suspense> */}
        <SideBar />
        <div className="flex-1 flex-col gap-8 pl-80">
        <NavBar title="Hello Hakim" />
          {children}
          </div>
          <Toaster />
      {/* </Suspense> */}
    </body>
    </html>
  );
}
